# Generated by Django 6.0.5 on 2026-05-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizApp", "0003_studentanswer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentanswer",
            name="correct_answer",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="studentanswer",
            name="selected_answer",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
