# Generated by Django 6.0.5 on 2026-05-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="time_limit",
            field=models.PositiveBigIntegerField(
                default=10, help_text="Duration in minutes"
            ),
        ),
    ]
